### ISSUE TITLE
Food mod Suggestion: UsefulFood (Or maybe a way for us to change the food value of a food mod)

### ISSUE THREAD

**Issue by Razorskills** [iguanaman/HungerOverhaul#19]
So I was just wondering if there might be a way to write item ids and their food value in a config to change the food value of mods that do not have current support.

I use this awesome food mod in my modpack, it adds maybe 50+ food items and all the recipes make sense and are quite awesome.

Here a link
http://www.minecraftforum.net/topic/1378111-162forge-usefulfood-144-craft-yourself-a-meal/

Feel free to close this if you do not what suggestion in your github.

**Comment by progwml6** [comment]
this stuff is being worked on for 1.7 as several of us are re-writing the mod to allow support for things like this

**Comment by Razorskills** [comment]
Old and already implemented.
